function dydt = Neuron(t,y,Params,Iin)
dydt = [(Iin/(Params.K*Params.Ith)-Params.Gamma_1*(y(1)-y(4)))/Params.tau_m;...
    (exp(-Params.K*Params.Beta*(y(1) + y(3)))*(1-exp(y(2)-Params.VDD))-exp(Params.K*y(1))*(1-exp(-y(2)))/Params.Gamma_2)/Params.tau_p;...
    (Params.IFGB/Params.Ith-((log((1+Params.E1*exp(Params.K*y(2)/2))./(1+Params.E1*exp((Params.K*y(2)-y(3))/2)))).^2))/Params.tau_out;...
    ((Params.Gamma_1*Params.K/(Params.E1^2))*(y(1)-y(4))-(1-exp(-y(4)))/exp(-Params.K*y(3)))/Params.tau_1];
end